use_frameworks!

platform :ios, '8.0'

target 'TestPodProject_Example' do
  pod 'TestPodProject', :path => '../'

  target 'TestPodProject_Tests' do
    inherit! :search_paths

  pod 'YYModel'
  end
end
